# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-25 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tutoria.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('isActive', models.IntegerField(choices=[(0, 0), (1, 1)])),
            ],
        ),
        migrations.CreateModel(
            name='BlackOutTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('status', models.CharField(blank=True, choices=[('booked', 'booked'), ('locked', 'locked'), ('in progress', 'in progress'), ('completed', 'completed'), ('reviewed', 'reviewed')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponCode', models.CharField(max_length=255)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=255)),
                ('courseName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Conversation')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationDetails', models.CharField(max_length=255)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('isRead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='passwordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('createDate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, choices=[('0', 'addCoins'), ('1', 'removeCoins'), ('2', 'sessionPayment'), ('3', 'sessionSalary'), ('4', 'sessionRefund')], max_length=2, null=True)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=255)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('isProcessed', models.BooleanField(default=False)),
                ('commision', models.DecimalField(decimal_places=1, default=0, max_digits=255)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Booking')),
                ('couponCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Coupon')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourlyRate', models.IntegerField()),
                ('tutorType', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('biography', models.TextField()),
                ('score', models.DecimalField(decimal_places=1, default=1.0, max_digits=2)),
                ('activated', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('courseCode', models.ManyToManyField(blank=True, null=True, to='tutoria.Course')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='tutoria.SubjectTag')),
            ],
        ),
        migrations.CreateModel(
            name='TutoriaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=tutoria.models.get_image_name)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('isActive', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('isStudent', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('isTutor', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('balance', models.DecimalField(decimal_places=1, max_digits=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='tutor',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.University'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.TutoriaUser'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.TutoriaUser'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.TutoriaUser'),
        ),
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Student'),
        ),
        migrations.AddField(
            model_name='review',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Tutor'),
        ),
        migrations.AddField(
            model_name='passwordtoken',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.TutoriaUser'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.TutoriaUser'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='tutoria.TutoriaUser'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='tutoria.TutoriaUser'),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.University'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='tutoria.TutoriaUser'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='tutoria.TutoriaUser'),
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Student'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.Tutor'),
        ),
        migrations.AddField(
            model_name='blackouttimeslot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoria.TutoriaUser'),
        ),
    ]
