# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-25 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0003_auto_20171125_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutoria.Booking'),
        ),
    ]
