# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-25 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='activated',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=1),
        ),
    ]
